kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - sleep 3s
  - echo hello
  - echo world2
  
- name: second_step
  image: alpine
  commands:
  - echo hello2
  - echo world2


- name: third_step
  image: alpine
  commands:
  - sleep 5s
  - echo hello3
  - echo world3
  depends_on:
  - greeting
  - second_step
