kind: pipeline
type: docker
name: hello

steps:
- name: greeting
  image: alpine
  commands:
  - sleep 3s
  - echo hello
  - echo world2
  
- name: second_step
  image: alpine
  commands:
  - echo hello2
  - echo world2
  
  depends_on:
  - greeting
  - second_step
